version: "3.8"


services:
  mysql:
    image: mysql:8
    container_name: collabrix-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: collabrix
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: .
      tags:
        - collabrix-backend
    container_name: collabrix-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      DB_URL: jdbc:mysql://mysql:3306/collabrix
      DB_USERNAME: root
      DB_PASSWORD: root

      MAIL_USERNAME: mehulkohad@gmail.com
      MAIL_PASSWORD: duqpphgtgnsvtafc
    ports:
      - "8080:8080"


volumes:
  mysql-data:
